apiVersion: apps/v1
kind: Deployment
metadata:
  name: eos-registry-api
  labels:
    app: eos-registry-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eos-registry-api
  template:
    metadata:
      labels:
        app: eos-registry-api
    spec:
      containers:
      - name: eos-registry-api
        image: dpthub/dpt8-registry:1.0
        ports:
        - containerPort: 8761
