apiVersion: apps/v1
kind: Deployment
metadata:
  name: eos-gateway-api
  labels:
    app: eos-gateway-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eos-gateway-api
  template:
    metadata:
      labels:
        app: eos-gateway-api
    spec:
      containers:
      - name: eos-gateway-api
        image: dpthub/dpt8-gw:1.0
        ports:
        - containerPort: 5555
