apiVersion: v1
kind: ServiceAccount
metadata:
  name: eos-svc-acc-01
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eos-svc-acc-01
  labels:
    "app.kubernetes.io/name": 'eos-svc-acc-01'
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eos-svc-acc-01
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eos-svc-acc-01
subjects:
- kind: ServiceAccount
  name: eos-svc-acc-01
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: eos-svc-acc-01
  annotations:
    kubernetes.io/service-account.name: eos-svc-acc-01
type: kubernetes.io/service-account-token